Add logo at browser tab
Pradumnasaraf/Post-My-Message pull request #23
Opened 2023-02-10 17:17 UTC by mithindev

## 🛠️ Fixes Issue

Closes #22 

## 👨‍💻 Changes proposed

The website is missing a distinctive and recognizable favicon, which can improve its overall appearance and make it easier for users to find and remember.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

The goal of this issue is to add a favicon to the website to improve its appearance and make it more memorable for users.

✔Create a square image to use as the favicon, with a recommended size of 16x16 pixels or 32x32 pixels.

✔Convert the image to the ICO format, which is the recommended format for favicons.

✔Upload the favicon to the root directory of the website.

✔Add the following code to the <head> section of the HTML file:

`<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">`

✔Replace /favicon.ico with the actual location and name of your favicon file.

2023-02-11 18:56 UTC, anand007s commented
> Can we merge this @Pradumnasaraf

2023-02-11 19:07 UTC, Pradumnasaraf requested changes
Hey,

The icon is not rendering. Looks like the error in naming.

Also, you created PR without getting the issue assigned and approval, which is a violation of CONTRIBUTING guidelines. I am closing this PR.

2023-02-11 19:07 UTC, Pradumnasaraf commented on public/index.html
> +    <link rel="shortcut icon" type="image/x-icon" href="/favicon1.ico">
```suggestion
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
```

2023-02-12 01:58 UTC, mithindev commented
I am really sorry, this won't happen again. Thank you so much for reviewing.

2023-02-12 06:45 UTC, Pradumnasaraf commented
Hey,

I just had a look the icon doesn't match the branding. Please use the below image. Also, use `href="favicon.ico"` syntax and remove the `/` 

![Untitled design](https://user-images.githubusercontent.com/51878265/218297084-82f2f3af-d1ef-441a-9dbc-2449663de5c8.png)

2023-02-12 06:54 UTC, mithindev commented
Ok. I will do it.

2023-02-12 15:29 UTC, mithindev commented
Hello @Pradumnasaraf . I have made the changes as you guided me. Thank you so much for your time.

2023-02-12 15:49 UTC, mithindev reviewed
Viewed for reviewing!

2023-02-14 08:16 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-14 08:16 UTC, merged

2023-02-14 09:28 UTC, mithindev commented
Thank you so much.